from typing import Protocol

from app.modules.pbl.application.records import (
    InferenceRequest,
    InferenceResult,
    PblDiagnosticRecord,
    PblParticipationRecord,
    PblReportParticipationRecord,
    PblSessionRecord,
    PblSnapshotRecord,
    PblSuggestionRecord,
)


class PblInferenceGateway(Protocol):
    def infer(self, request: InferenceRequest) -> InferenceResult: ...


class PblRepository(Protocol):
    def create_session(
        self,
        class_id: int,
        teacher_id: int,
        topic_code: str,
        provider: str,
        mode: str | None,
        context: dict,
        goals: tuple[str, ...],
    ) -> PblSessionRecord: ...
    def get_session(self, session_id: int) -> PblSessionRecord | None: ...
    def close_session(self, session_id: int) -> PblSessionRecord: ...
    def list_active_sessions(self, class_ids: tuple[int, ...], student_id: int) -> tuple[PblSessionRecord, ...]: ...
    def list_sessions_for_teacher(self, teacher_id: int, class_id: int) -> tuple[PblSessionRecord, ...]: ...
    def get_or_create_participation(self, session_id: int, student_id: int) -> PblParticipationRecord: ...
    def participation(self, participation_id: int) -> PblParticipationRecord | None: ...
    def latest_snapshot(self, participation_id: int) -> PblSnapshotRecord | None: ...
    def append_student_message(
        self, participation_id: int, client_message_id: str, content: str
    ) -> PblParticipationRecord | None: ...
    def save_result(
        self, participation_id: int, revision: int, result: InferenceResult
    ) -> PblSnapshotRecord | None: ...
    def diagnostics_for_teacher(
        self, teacher_id: int, limit: int, offset: int, filters: dict
    ) -> tuple[tuple[PblDiagnosticRecord, ...], int]: ...
    def diagnostic_for_teacher(self, teacher_id: int, snapshot_id: int) -> PblDiagnosticRecord | None: ...
    def suggestion_for_teacher(self, teacher_id: int, suggestion_id: int) -> PblSuggestionRecord | None: ...
    def session_for_suggestion(self, suggestion_id: int) -> PblSessionRecord | None: ...
    def update_suggestion(
        self, suggestion_id: int, title: str, prompt: str, status: str, version: int
    ) -> PblSuggestionRecord: ...
    def attach_problem(self, suggestion_id: int, problem_id: int, version: int) -> PblSuggestionRecord: ...

    def find_participation(self, session_id: int, student_id: int) -> PblParticipationRecord | None: ...
    def message_result(self, participation_id: int, client_message_id: str) -> PblSnapshotRecord | None: ...
    def revisions_for_teacher(self, teacher_id: int, snapshot_id: int) -> tuple[PblDiagnosticRecord, ...]: ...
    def session_counts(self, session_id: int) -> dict[str, int]: ...
    def report_participations(self, student_id: int) -> tuple[PblReportParticipationRecord, ...]: ...
