from typing import Protocol

from app.modules.pbl.application.records import (
    InferenceRequest,
    InferenceResult,
    PblDiagnosticRecord,
    PblMessageResultRecord,
    PblParticipationRecord,
    PblPrivateFollowUpResultRecord,
    PblSessionRecord,
    PblSnapshotRecord,
    PrivateFollowupRequest,
    PrivateFollowupResult,
)


class PblInferenceGateway(Protocol):
    def infer(self, request: InferenceRequest) -> InferenceResult: ...
    def private_follow_up(self, request: PrivateFollowupRequest) -> PrivateFollowupResult: ...


class PblRepository(Protocol):
    def create_session(
        self,
        class_id: int | None,
        teacher_id: int | None,
        topic_code: str,
        provider: str,
        mode: str | None,
        context: dict,
        goals: tuple[str, ...],
        session_kind: str = "classroom",
        created_by_student_id: int | None = None,
        client_session_id: str | None = None,
    ) -> PblSessionRecord: ...
    def get_session(self, session_id: int) -> PblSessionRecord | None: ...
    def close_session(self, session_id: int) -> PblSessionRecord: ...
    def list_active_sessions(self, class_ids: tuple[int, ...], student_id: int) -> tuple[PblSessionRecord, ...]: ...
    def list_sessions_for_teacher(self, teacher_id: int, class_id: int) -> tuple[PblSessionRecord, ...]: ...
    def list_sessions_owned_by_teacher(self, teacher_id: int) -> tuple[PblSessionRecord, ...]: ...
    def session_dashboard_rows(self, session_id: int) -> tuple[dict, ...]: ...
    def get_or_create_participation(
        self, session_id: int, student_id: int, interaction_style: str = "guided"
    ) -> PblParticipationRecord: ...
    def find_student_session_by_client_id(self, student_id: int, client_session_id: str) -> PblSessionRecord | None: ...
    def set_interaction_style(self, participation_id: int, interaction_style: str) -> PblParticipationRecord: ...
    def participation(self, participation_id: int) -> PblParticipationRecord | None: ...
    def latest_snapshot(self, participation_id: int) -> PblSnapshotRecord | None: ...
    def completion_snapshot(self, participation_id: int) -> PblSnapshotRecord | None: ...
    def student_dialogues_for_point(self, student_id: int, point_code: str) -> tuple[dict, ...]: ...
    def append_student_message(
        self, participation_id: int, client_message_id: str, content: str, interaction_style: str, turn_scope: str
    ) -> PblParticipationRecord | None: ...
    def save_result(
        self, participation_id: int, revision: int, result: InferenceResult
    ) -> PblSnapshotRecord | None: ...
    def save_private_follow_up_result(
        self, participation_id: int, revision: int, result: PrivateFollowupResult
    ) -> PblPrivateFollowUpResultRecord | None: ...
    def diagnostics_for_teacher(
        self, teacher_id: int, limit: int, offset: int, filters: dict
    ) -> tuple[tuple[PblDiagnosticRecord, ...], int]: ...
    def diagnostic_for_teacher(self, teacher_id: int, snapshot_id: int) -> PblDiagnosticRecord | None: ...

    def find_participation(self, session_id: int, student_id: int) -> PblParticipationRecord | None: ...
    def message_result(self, participation_id: int, client_message_id: str) -> PblMessageResultRecord | None: ...
    def revisions_for_teacher(self, teacher_id: int, snapshot_id: int) -> tuple[PblDiagnosticRecord, ...]: ...
    def session_counts(self, session_id: int) -> dict[str, int]: ...
