import { expect, test } from '@playwright/test'

test('student learning groups cases, knowledge, and questions behind one secondary resource page', async ({ page }) => {
  await page.goto('/')
  await page.locator('.role-button.student').click()
  await page.locator('.student-nav__item').filter({ hasText: '学习' }).click()
  await expect(page.locator('.student-nav__item')).toHaveCount(3)
  await expect(page.getByText('自主训练', { exact: true })).toBeVisible()
  await page.locator('.resource-row').filter({ hasText: '病例训练' }).click()
  await expect(page.locator('.resource-tab')).toHaveCount(3)
  await expect(page.locator('.resource-tab.active')).toHaveText('病例')
  await page.locator('.resource-tab').filter({ hasText: '知识' }).click()
  await expect(page.getByText('病理学知识地图', { exact: true })).toBeVisible()
  await page.locator('.resource-tab').filter({ hasText: '练习' }).click()
  await expect(page.getByText('PBL 讨论题', { exact: true })).toBeVisible()
  await page.locator('.student-nav__item').filter({ hasText: '学习' }).click()
  await expect(page.getByText('自主训练', { exact: true })).toBeVisible()
})

test('Demo keeps legacy QA read-only and starts new work in the unified dialogue without API requests', async ({
  page,
}) => {
  const apiRequests: string[] = []
  page.on('request', (request) => {
    if (/\/(conversations|reports|student\/questions)(\?|$)/.test(new URL(request.url()).pathname))
      apiRequests.push(request.url())
  })
  await page.goto('/')
  await page.locator('.role-button.student').click()
  await page.locator('.account-bar uni-button').filter({ hasText: '历史答疑' }).click()
  await page.locator('.history-card').first().click()
  await expect(page.getByText('旧答疑只读保留', { exact: true })).toBeVisible()
  await expect(page.locator('textarea')).toHaveCount(0)
  await expect(page.locator('.report-button')).toHaveCount(0)
  await page.getByText('以此主题开始新研讨', { exact: true }).click()
  await expect(page.getByText('开始一次病理研讨', { exact: true })).toBeVisible()
  await page.getByText('退出', { exact: true }).click()
  expect(apiRequests).toEqual([])
})

test('Demo PBL automatically activates a failed target and exhausts after the second cycle', async ({ page }) => {
  await page.goto('/')
  await page.locator('.role-button.student').click()
  await expect(page.locator('[aria-label="研讨上下文"]')).toBeVisible()
  await page.getByText('确认并开始', { exact: true }).click()
  const question = page.locator('textarea').first()
  for (const [answer, phase] of [
    ['局部红肿涉及血管反应，我先明确需要解释的问题。', '提出假设'],
    ['我假设血流增加与通透性升高共同导致红肿，但仍不确定。', '讨论证据'],
    ['血管扩张支持红，渗出支持肿，但需要考虑证据限制。', '总结解释'],
    ['综合机制与证据后保留疑问，需要再核对通透性变化。', '已完成'],
  ] as const) {
    const submit = page.locator('.composer uni-button')
    await question.fill(answer)
    await expect(submit).not.toHaveAttribute('disabled')
    await submit.click()
    await expect(page.locator('.meta-chip').filter({ hasText: phase })).toBeVisible()
    if (phase !== '已完成') await expect(question).toHaveValue('')
  }
  await page.locator('.student-nav__item').filter({ hasText: '学情' }).click()
  await expect(page.getByText('当前重点', { exact: true })).toBeVisible()
  await expect(page.getByText('待发布学习', { exact: true }).first()).toBeVisible()
  await page.locator('.report-row').first().click()
  await expect(page.getByText('四阶段讨论证据', { exact: true })).toBeVisible()
  await page.goBack()
  await expect(page.getByText('当前重点', { exact: true })).toBeVisible()
  await page.locator('.student-nav__item').filter({ hasText: '研讨' }).click()
  await page.getByText('退出', { exact: true }).click()

  await page.locator('.role-button.teacher').click()
  await page.locator('.teacher-nav__item').filter({ hasText: 'PBL' }).click()
  await expect(page.getByText('诊断待办', { exact: true })).toBeVisible()
  await page.getByText('采用并发布', { exact: true }).click()
  await expect(page.locator('.suggestion uni-button').filter({ hasText: '已发布' })).toBeVisible()
  await page.getByText('退出', { exact: true }).click()

  await page.locator('.role-button.student').click()
  await page.locator('.student-nav__item').filter({ hasText: '学习' }).click()
  for (let step = 0; step < 3; step += 1) {
    const task = page.locator('.task--next')
    await expect(task).toBeVisible()
    const title = await task.locator('.subtitle').innerText()
    if (title.includes('正式讨论题')) await task.locator('textarea').fill('提交首轮证据链。')
    else if (title.includes('知识巩固')) await task.locator('uni-label').nth(0).click()
    else await task.locator('uni-label').nth(1).click()
    await expect(task.locator('uni-button.primary')).not.toHaveAttribute('disabled')
    await task.getByText('完成这一步', { exact: true }).click()
    await expect(page.locator('.task--next .subtitle')).not.toHaveText(title)
  }
  await expect(page.getByText(/当前第 2\/2 轮/)).toBeVisible()
  const cycleTwoTasks = page.locator('.task--next')
  await cycleTwoTasks.locator('textarea').fill('第二轮重新说明证据链与不确定性。')
  await expect(cycleTwoTasks.locator('uni-button.primary')).not.toHaveAttribute('disabled')
  const discussionTitle = await cycleTwoTasks.locator('.subtitle').innerText()
  await cycleTwoTasks.getByText('完成这一步', { exact: true }).click()
  await expect(page.locator('.task--next .subtitle')).not.toHaveText(discussionTitle)
  await page.locator('.task--next uni-label').nth(0).click()
  await expect(page.locator('.task--next uni-button.primary')).not.toHaveAttribute('disabled')
  const reviewTitle = await page.locator('.task--next .subtitle').innerText()
  await page.locator('.task--next').getByText('完成这一步', { exact: true }).click()
  await expect(page.locator('.task--next .subtitle')).not.toHaveText(reviewTitle)
  await page.locator('.task--next uni-label').nth(1).click()
  await expect(page.locator('.task--next uni-button.primary')).not.toHaveAttribute('disabled')
  await page.locator('.task--next').getByText('完成这一步', { exact: true }).click()

  await expect(page.getByText('需继续巩固', { exact: true })).toBeVisible()
  await expect(page.getByText('自动轮次已结束，仍有目标需线下支持。', { exact: true })).toBeVisible()
  await page.locator('.student-nav__item').filter({ hasText: '学情' }).click()
  await expect(page.getByText('需线下支持', { exact: true }).first()).toBeVisible()
  await page.locator('.report-row').first().click()
  await expect(page.getByText('目标改善对照', { exact: true })).toBeVisible()
  await expect(page.getByText('自动轮次结束，仍需线下支持', { exact: true })).toBeVisible()
  await page.goBack()
  await expect(page.getByText('当前重点', { exact: true })).toBeVisible()
  await page.locator('.student-nav__item').filter({ hasText: '研讨' }).click()
  await page.getByText('退出', { exact: true }).click()
  await page.locator('.role-button.teacher').click()
  await page.locator('.teacher-nav__item').filter({ hasText: 'PBL' }).click()
  await expect(page.getByText(/自动轮次已结束，需线下支持/)).toBeVisible()
  await expect(page.getByRole('button', { name: '确认已改善' })).toHaveCount(0)
  await expect(page.getByRole('button', { name: '继续巩固' })).toHaveCount(0)
})
