import { expect, test } from '@playwright/test'

test('student completes the structured five-stage showcase case', async ({ page }) => {
  await page.goto('/')
  await page.locator('.role-button.student').click()
  await page.locator('.student-nav__item').filter({ hasText: '病例' }).click()
  await expect(page.getByText('社区获得性肺炎：结构化临床推理')).toBeVisible()
  await page.getByText('社区获得性肺炎：结构化临床推理').click()
  await expect(page.getByText('虚拟患者对话')).toBeVisible()
  await page.locator('input').first().fill('发热多久，最高体温多少？')
  await page.getByText('询问患者', { exact: true }).click()
  await expect(page.getByText(/39.1℃/)).toBeVisible()
  await page.locator('textarea').nth(0).fill('急性发热咳嗽3天')
  await page.locator('textarea').nth(1).fill('发热')
  await page.getByText('提交病史采集', { exact: true }).click()
  await expect(page.getByText('提交问题表征', { exact: true })).toBeVisible()

  await page.locator('textarea').first().fill('急性发热咳嗽，考虑肺部感染')
  await page.getByText('提交问题表征', { exact: true }).click()
  await expect(page.getByText('鉴别诊断（每行：诊断｜支持证据｜反对证据）', { exact: true })).toHaveCount(0)
  await expect(page.locator('.answer-card')).toHaveCount(2)

  const differential = page.locator('.answer-card')
  await differential.nth(0).locator('input').fill('社区获得性肺炎')
  await differential.nth(0).locator('textarea').nth(0).fill('发热')
  await differential.nth(1).locator('input').fill('病毒性肺炎')
  await differential.nth(1).locator('textarea').nth(0).fill('咳嗽')
  await page.getByText('提交鉴别诊断', { exact: true }).click()
  await expect(page.getByText('检查决策卡片', { exact: true })).toBeVisible()

  await page.locator('.answer-card').first().locator('input').nth(0).fill('胸部影像')
  await page.locator('.answer-card').first().locator('textarea').fill('确认浸润')
  await page.getByText('提交检查决策', { exact: true }).click()
  await expect(page.getByText('初步处置卡片', { exact: true })).toBeVisible()

  await page.locator('.answer-card').first().locator('input').nth(0).fill('评估氧合和严重程度')
  await page.locator('.answer-card').first().locator('textarea').fill('保障安全')
  await page.locator('textarea').last().fill('药物过敏')
  await page.getByText('提交初步处置', { exact: true }).click()
  await page.getByText('生成训练报告', { exact: true }).click()
  await expect(page.getByText('六维评价')).toBeVisible()
})
