from app.schemas.auth import LoginRequest, LoginResponse, UserRead, WechatLoginRequest
from app.schemas.classroom import (
    AnalyticsCaseRead,
    AnalyticsOverview,
    AnalyticsStudentRead,
    ClassCreate,
    ClassMemberCreate,
    ClassRead,
    ClassStudentRead,
    ClassUpdate,
    MedicalReviewRead,
    MedicalReviewViewRead,
    ReviewSubmit,
)
from app.schemas.conversation import ConversationRead, ConversationUpsert, MessageIn, MessageRead
from app.schemas.medical_ai import MedicalChatRequest, MedicalChatResponse
from app.schemas.personalized import (
    LearningPlanRead,
    LearningProfileRead,
    LearningTaskAttemptRead,
    LearningTaskPublic,
    LearningTaskStartRead,
    LearningTaskSubmit,
    NotificationListRead,
    NotificationRead,
)
from app.schemas.problem import (
    ProblemAuthoringRead,
    ProblemCreate,
    ProblemRead,
    ProblemUpdate,
    QuestionThreadRead,
    QuestionThreadUpsert,
)
from app.schemas.report import ReportAnalysis, ReportCreate, ReportRead, ReportReview

__all__ = [
    "ConversationRead",
    "ConversationUpsert",
    "LoginRequest",
    "LoginResponse",
    "WechatLoginRequest",
    "MedicalChatRequest",
    "MedicalChatResponse",
    "MessageIn",
    "MessageRead",
    "ProblemCreate",
    "ProblemAuthoringRead",
    "ProblemRead",
    "ProblemUpdate",
    "QuestionThreadRead",
    "QuestionThreadUpsert",
    "ReportCreate",
    "ReportAnalysis",
    "ReportRead",
    "ReportReview",
    "UserRead",
    "ClassCreate",
    "ClassUpdate",
    "ClassMemberCreate",
    "ClassRead",
    "ClassStudentRead",
    "ReviewSubmit",
    "MedicalReviewRead",
    "MedicalReviewViewRead",
    "AnalyticsOverview",
    "AnalyticsCaseRead",
    "AnalyticsStudentRead",
    "LearningPlanRead",
    "LearningProfileRead",
    "LearningTaskAttemptRead",
    "LearningTaskPublic",
    "LearningTaskStartRead",
    "LearningTaskSubmit",
    "NotificationListRead",
    "NotificationRead",
]
