from __future__ import annotations

from typing import Protocol

from app.modules.content.application.records import (
    CaseDraftResult,
    KnowledgeCardContributionCommand,
    KnowledgeCardContributionRecord,
    ProblemCommand,
    ProblemRecord,
    ReviewRecord,
)
from app.shared.actor import Actor


class ProblemRepository(Protocol):
    def class_codes(self, student_id: int) -> set[str]: ...

    def list_all(self) -> tuple[ProblemRecord, ...]: ...

    def list_visible_for_student(self, student: Actor, class_codes: set[str]) -> tuple[ProblemRecord, ...]: ...

    def get(self, problem_id: int) -> ProblemRecord | None: ...

    def create(self, teacher_id: int, command: ProblemCommand) -> ProblemRecord: ...

    def update(self, problem_id: int, teacher_id: int, command: ProblemCommand) -> ProblemRecord: ...

    def clone(self, problem: ProblemRecord, teacher_id: int) -> ProblemRecord: ...

    def publish(self, problem_id: int) -> ProblemRecord: ...

    def reject(self, problem_id: int) -> ProblemRecord: ...

    def invalidate_review(self, problem_id: int) -> None: ...

    def latest_approved_review_digest(self, problem_id: int) -> str | None: ...

    def answer_counts(self, problem_ids: list[int]) -> dict[int, int]: ...

    def review_queue(self, status: str) -> tuple[ProblemRecord, ...]: ...

    def submit_review(self, problem_id: int, teacher_id: int) -> ProblemRecord: ...

    def add_review(self, problem_id: int, reviewer_id: int, decision: str, comment: str) -> ProblemRecord: ...

    def review_view(self, problem_id: int) -> tuple[ProblemRecord, str | None, tuple[ReviewRecord, ...]]: ...

    def review_history(self, problem_id: int) -> tuple[ReviewRecord, ...]: ...

    def teacher_owns_class(self, teacher_id: int, class_code: str) -> bool: ...

    def create_knowledge_card(
        self, owner_id: int, command: KnowledgeCardContributionCommand
    ) -> KnowledgeCardContributionRecord: ...

    def update_knowledge_card(
        self, card_id: int, owner_id: int, command: KnowledgeCardContributionCommand
    ) -> KnowledgeCardContributionRecord: ...

    def get_knowledge_card(self, card_id: int) -> KnowledgeCardContributionRecord | None: ...

    def list_knowledge_cards_for_owner(self, owner_id: int) -> tuple[KnowledgeCardContributionRecord, ...]: ...

    def list_knowledge_cards_by_status(self, status: str) -> tuple[KnowledgeCardContributionRecord, ...]: ...

    def list_visible_knowledge_cards(
        self, student_id: int, class_codes: set[str], point_code: str | None
    ) -> tuple[KnowledgeCardContributionRecord, ...]: ...

    def submit_knowledge_card(self, card_id: int) -> KnowledgeCardContributionRecord: ...

    def decide_knowledge_card(
        self, card_id: int, reviewer_id: int, decision: str, comment: str
    ) -> KnowledgeCardContributionRecord: ...

    def disable_knowledge_card(self, card_id: int) -> KnowledgeCardContributionRecord: ...


class CaseDraftGenerator(Protocol):
    def generate(self, topic: str, learner_level: str, objectives: list[str], teacher_id: int) -> CaseDraftResult: ...


class CaseDraftAudit(Protocol):
    def record_ai_call(
        self,
        *,
        user_id: int,
        model_name: str,
        prompt_version: str,
        latency_ms: int,
        fallback_used: bool,
        failure_reason: str | None,
    ) -> None: ...
