from typing import Protocol

from app.modules.classroom.public import ClassroomScopePort
from app.modules.content.public import KnowledgeCatalogPort


class LearningRouteInferencePort(Protocol):
    def execute_task(self, task_kind: str, request_id: str, input_payload: dict) -> dict: ...


class LearningRouteStore(Protocol):
    def teacher_review_candidates(self, teacher_id: int, filters: dict) -> list[dict]: ...

    def review_locator(self, teacher_id: int, participation_id: int) -> dict | None: ...
    def classroom_progress(self, teacher_id: int, class_id: int, session_id: int) -> list[dict]: ...
    def teacher_result(self, teacher_id: int, result_id: str) -> dict: ...
    def queue_generation(self, route_id: str, component: str, actor_id: int, request_id: str) -> dict: ...
    def ensure_shell(self, context: dict) -> dict: ...
    def route(self, public_id: str) -> dict | None: ...
    def list_routes(self, student_id: int, status: str, limit: int, offset: int) -> dict: ...
    def detail(self, public_id: str) -> dict: ...
    def step(self, public_id: str) -> dict | None: ...
    def reading_progress(self, step_id: str, action: str, lease: str | None, request_id: str) -> dict: ...
    def complete_reading(self, step_id: str, request_id: str) -> dict: ...
    def case(self, public_id: str) -> dict | None: ...
    def claim_case_message(self, public_id: str, message_id: str, content: str, revision: int) -> dict: ...
    def save_case_reply(self, public_id: str, claim: dict, result: dict) -> dict: ...
    def fail_case_reply(self, public_id: str, claim: dict) -> None: ...
    def test(self, public_id: str) -> dict | None: ...
    def start_test(self, public_id: str, request_id: str) -> dict: ...
    def student_test(self, route_id: str) -> dict: ...
    def save_draft(self, test_id: str, payload: dict) -> dict: ...
    def prepare_submission(self, test_id: str, payload: dict) -> dict: ...
    def grading_status(self, test_id: str) -> dict: ...
    def claim_grading(self, test_id: str) -> dict: ...
    def finish_grading(self, test_id: str, claim: dict, result: dict) -> dict: ...
    def fail_grading(self, test_id: str, claim: dict) -> None: ...
    def result(self, route_id: str) -> dict | None: ...
    def result_locator(self, result_id: str) -> dict | None: ...
    def tutor_read(self, result_id: str) -> dict: ...
    def claim_tutor_message(self, result_id: str, payload: dict) -> dict: ...
    def save_tutor_reply(self, result_id: str, claim: dict, reply: dict) -> dict: ...
    def fail_tutor_reply(self, result_id: str, claim: dict) -> None: ...
    def teacher_tests(self, teacher_id: int, filters: dict) -> dict: ...
    def teacher_test(self, test_id: str) -> dict: ...
    def save_teacher_test(self, test_id: str, payload: dict) -> dict: ...
    def release_test(self, test_id: str, teacher_id: int, payload: dict) -> dict: ...
    def request_changes(self, test_id: str, teacher_id: int, payload: dict) -> dict: ...
    def teacher_results(self, teacher_id: int, filters: dict) -> dict: ...
    def claim_generation(self, route_id: str, component: str, token: str | None = None) -> dict: ...
    def generation_input(self, route_id: str, component: str) -> dict: ...
    def publish_generation(self, route_id: str, component: str, claim: dict, result: dict) -> None: ...
    def fail_generation(self, route_id: str, component: str, claim: dict) -> None: ...


__all__ = ["LearningRouteStore", "LearningRouteInferencePort", "ClassroomScopePort", "KnowledgeCatalogPort"]
