from typing import Protocol


class StudyRepository(Protocol):
    def paths(self, student_id: int, point_code: str) -> list[dict]: ...
    def path(self, student_id: int, path_id: int) -> dict | None: ...
    def save_path(self, student_id: int, point_code: str, session_id: int, client_id: str, version: str) -> dict: ...
    def legacy_access(self, student_id: int, point_code: str) -> bool: ...
    def groups(self, student_id: int, path_id: int | None = None) -> list[dict]: ...
    def group(self, student_id: int, group_id: int) -> dict | None: ...
    def claim_group(self, path: dict, cycle: int, client_id: str, snapshot_id: int) -> dict: ...
    def finish_group(self, group_id: int, claim: str, questions: list[dict], failure: str | None) -> bool: ...
    def attempts(self, student_id: int, group_id: int) -> list[dict]: ...
    def save_attempt(self, student_id: int, group_id: int, question_index: int, client_id: str,
                     selected_option: int, correct: bool) -> dict: ...


class PracticeGenerator(Protocol):
    def generate(self, context: dict) -> list[dict]: ...
