from __future__ import annotations

from typing import Protocol

from app.modules.classroom.application.records import (
    ClassCommand,
    ClassRecord,
    ClassStudentRecord,
    ClassUpdateCommand,
)


class ClassroomRepository(Protocol):
    def list_for_teacher(self, teacher_id: int) -> tuple[ClassRecord, ...]: ...

    def create(self, teacher_id: int, command: ClassCommand) -> ClassRecord: ...

    def find_owned(self, class_id: int, teacher_id: int) -> ClassRecord | None: ...

    def update(self, class_id: int, command: ClassUpdateCommand) -> ClassRecord: ...

    def list_students(self, class_id: int) -> tuple[ClassStudentRecord, ...]: ...

    def student_exists(self, student_id: int) -> bool: ...

    def student_id_by_external_id(self, external_id: str) -> int | None: ...

    def member_exists(self, class_id: int, student_id: int) -> bool: ...

    def add_member(self, class_id: int, student_id: int) -> None: ...

    def remove_member(self, class_id: int, student_id: int) -> None: ...
